export default [
  {
    breeds: [
      {
        weight: {
          imperial: "8 - 16",
          metric: "4 - 7",
        },
        id: "amau",
        name: "Arabian Mau",
        vcahospitals_url: "",
        temperament:
          "Affectionate, Agile, Curious, Independent, Playful, Loyal",
        origin: "United Arab Emirates",
        country_codes: "AE",
        country_code: "AE",
        description:
          "Arabian Mau cats are social and energetic. Due to their energy levels, these cats do best in homes where their owners will be able to provide them with plenty of playtime, attention and interaction from their owners. These kitties are friendly, intelligent, and adaptable, and will even get along well with other pets and children.",
        life_span: "12 - 14",
        indoor: 0,
        alt_names: "Alley cat",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 1,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 1,
        social_needs: 3,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Arabian_Mau",
        hypoallergenic: 0,
        reference_image_id: "k71ULYfRr",
      },
    ],
    id: "m1TeHn2dH",
    url: "https://cdn2.thecatapi.com/images/m1TeHn2dH.jpg",
    width: 3555,
    height: 2569,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "4 - 10",
          metric: "2 - 5",
        },
        id: "bali",
        name: "Balinese",
        cfa_url: "http://cfa.org/Breeds/BreedsAB/Balinese.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/balinese",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/balinese",
        temperament: "Affectionate, Intelligent, Playful",
        origin: "United States",
        country_codes: "US",
        country_code: "US",
        description:
          "Balinese are curious, outgoing, intelligent cats with excellent communication skills. They are known for their chatty personalities and are always eager to tell you their views on life, love, and what you’ve served them for dinner. ",
        life_span: "10 - 15",
        indoor: 0,
        alt_names: "Long-haired Siamese",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 3,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Balinese_(cat)",
        hypoallergenic: 1,
        reference_image_id: "13MkvUreZ",
      },
    ],
    id: "4ndvXwCiI",
    url: "https://cdn2.thecatapi.com/images/4ndvXwCiI.jpg",
    width: 1280,
    height: 960,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "5 - 11",
          metric: "2 - 5",
        },
        id: "sfol",
        name: "Scottish Fold",
        cfa_url: "http://cfa.org/Breeds/BreedsSthruT/ScottishFold.aspx",
        vetstreet_url:
          "http://www.vetstreet.com/cats/scottish-fold-highland-fold",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/scottish-fold",
        temperament:
          "Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving",
        origin: "United Kingdom",
        country_codes: "GB",
        country_code: "GB",
        description:
          'The Scottish Fold is a sweet, charming breed. She is an easy cat to live with and to care for. She is affectionate and is comfortable with all members of her family. Her tail should be handled gently. Folds are known for sleeping on their backs, and for sitting with their legs stretched out and their paws on their belly. This is called the "Buddha Position".',
        life_span: "11 - 14",
        indoor: 0,
        alt_names: "Scot Fold",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 1,
        health_issues: 4,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 3,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Scottish_Fold",
        hypoallergenic: 0,
        reference_image_id: "o9t0LDcsa",
      },
    ],
    id: "Z6d8vsYAo",
    url: "https://cdn2.thecatapi.com/images/Z6d8vsYAo.jpg",
    width: 1280,
    height: 1098,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "7 - 12",
          metric: "3 - 5",
        },
        id: "ctif",
        name: "Chantilly-Tiffany",
        temperament: "Affectionate, Demanding, Interactive, Loyal",
        origin: "United States",
        country_codes: "US",
        country_code: "US",
        description:
          'The Chantilly is a devoted companion and prefers company to being left alone. While the Chantilly is not demanding, she will "chirp" and "talk" as if having a conversation. This breed is affectionate, with a sweet temperament. It can stay still for extended periods, happily lounging in the lap of its loved one. This quality makes the Tiffany an ideal traveling companion, and an ideal house companion for senior citizens and the physically handicapped.',
        life_span: "14 - 16",
        indoor: 0,
        lap: 1,
        alt_names: "Chantilly, Foreign Longhair",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 5,
        health_issues: 1,
        intelligence: 5,
        shedding_level: 5,
        social_needs: 3,
        stranger_friendly: 4,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Chantilly-Tiffany",
        hypoallergenic: 0,
        reference_image_id: "TR-5nAd_S",
      },
    ],
    id: "XAvnPwmqZ",
    url: "https://cdn2.thecatapi.com/images/XAvnPwmqZ.jpg",
    width: 1200,
    height: 797,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "8 - 16",
          metric: "4 - 7",
        },
        id: "cypr",
        name: "Cyprus",
        temperament: "Affectionate, Social",
        origin: "Cyprus",
        country_codes: "CY",
        country_code: "CY",
        description:
          "Loving, loyal, social and inquisitive, the Cyprus cat forms strong ties with their families and love nothing more than to be involved in everything that goes on in their surroundings. They are not overly active by nature which makes them the perfect companion for people who would like to share their homes with a laid-back relaxed feline companion. ",
        life_span: "12 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "Cypriot cat",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 3,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 3,
        stranger_friendly: 4,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Cyprus_cat",
        hypoallergenic: 0,
        reference_image_id: "tJbzb7FKo",
      },
    ],
    id: "cruhNBsv1",
    url: "https://cdn2.thecatapi.com/images/cruhNBsv1.jpg",
    width: 1024,
    height: 768,
  },
];
